# https://docs.travis-ci.com/user/languages/python/
dist: xenial
language: python
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- make BINPREFIX= deps
- pip install coveralls
script:
- make BINPREFIX= covercheck
after_success: coveralls
notifications:
  email: false
